raft:
  nodes:
    - id: node1
      address: 127.0.0.1:5000
    - id: node2
      address: 127.0.0.1:5001
    - id: node3
      address: 127.0.0.2:5000
    - id: node4
      address: 127.0.0.3:5000
    - id: node5
      address: 192.168.1.5:5000
  electionTimeout: 150
  heartbeatInterval: 50
  logDirectory: /var/log/raft
